#
# Github action that creates a .love artifact
#
name: Deploy .love

on:
  # Only do manual triggers while developing workflow
  workflow_dispatch:

jobs:
  build-MovieMonsters:
    runs-on: ubuntu-latest
    steps:
    # checkout the repository
    - uses: actions/checkout@v2

    # build the artifacts
    - name: LÖVE Build
      id: love-build
      uses: nhartland/love-build@v1-beta3
      with:
        app_name: "MovieMonsters"
        love_version: "11.3"

    # Upload the resulting artifacts
    - name: LÖVE mac OSX upload
      uses: actions/upload-artifact@v1
      with:
        name: mm_macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}

    - name: LÖVE win32 upload
      uses: actions/upload-artifact@v1
      with:
        name: mm_win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}

    - name: LÖVE win64 upload
      uses: actions/upload-artifact@v1
      with:
        name: mm_win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}

    - name: .love file upload
      uses: actions/upload-artifact@v1
      with:
        name: mm_love-build
        path: ${{ steps.love-build.outputs.love-filename }}

    - name: Release when on a tag
      uses: fnkr/github-action-ghr@v1
#      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

