#
# Github action that creates a .love artifact
#
name: Generate a release

on:
  # Only do manual triggers while developing workflow
  workflow_dispatch:

jobs:
  build-MovieMonsters:
    runs-on: ubuntu-latest
    steps:
    # checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Test
    # TODO: I need to add a testing/checking phase here

    # Build
    - name: Build
      id: love-build
      uses: nhartland/love-build@v1-beta3
      with:
        app_name: "MovieMonsters"
        love_version: "11.3"

    # Upload the resulting artifacts
    - name: Artifact for OSX
      uses: actions/upload-artifact@v1
      with:
        name: mm_macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}

    - name: Artifact for win32
      uses: actions/upload-artifact@v1
      with:
        name: mm_win32-build
        path: ${{ steps.love-build.outputs.win32-filename }}

    - name: Artifact for win64
      uses: actions/upload-artifact@v1
      with:
        name: mm_win64-build
        path: ${{ steps.love-build.outputs.win64-filename }}

    - name: Artifact for .love file
      uses: actions/upload-artifact@v1
      with:
        name: mm_love-build
        path: ${{ steps.love-build.outputs.love-filename }}

    - name: Release # on tag only
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          MovieMonsters_macos.zip
          MovieMonsters_win32.zip
          MovieMonsters_win64.zip
          MovieMonsters.love
        fail_on_unmatched_files: true
        draft: true
        name: "v0.0.0"
        prerelease: true
